###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"email@email.com",
    "password":"password"
}

###
GET http://localhost:3000/auth/testing
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiZW1haWxAZW1haWwuY29tIiwiaWF0IjoxNjE0NTExNDY2LCJleHAiOjE2MTQ1MTg2NjZ9.gWP4bzibXW89zQryyjRTVo5LiB81Q_MgybuvF2APqhPRVFqE0HA0heXoIwsA-WjT95IavO8-4P53nL24bink6g